// Seed data for Просвіт: 6 organizations, 30 events across Київ/Львів/Дніпро,
// 26 ghost veterans (with realistic Ukrainian first names; persona names
// Дмитро/Катерина/Михайло/Василь are deliberately excluded).

import type { AccessibilityFlag, IdentityPref, InterestCategory } from "@poruch/shared";

export const SEED_ORG_MARKER = "[seed]";
export const SEED_GHOST_MARKER = "[seed-ghost]";

// --------------------------------------------------------------
// Cities
// --------------------------------------------------------------
export type SeedCity = {
  slug: string;
  name_uk: string;
  oblast: string;
  population: number;
  is_demo_city: boolean;
};

export const SEED_CITIES: SeedCity[] = [
  { slug: "kyiv", name_uk: "Київ", oblast: "Київська", population: 2950000, is_demo_city: true },
  { slug: "lviv", name_uk: "Львів", oblast: "Львівська", population: 717000, is_demo_city: true },
  {
    slug: "dnipro",
    name_uk: "Дніпро",
    oblast: "Дніпропетровська",
    population: 968000,
    is_demo_city: true,
  },
  {
    slug: "kharkiv",
    name_uk: "Харків",
    oblast: "Харківська",
    population: 1400000,
    is_demo_city: false,
  },
  { slug: "odesa", name_uk: "Одеса", oblast: "Одеська", population: 1010000, is_demo_city: false },
  {
    slug: "vinnytsia",
    name_uk: "Вінниця",
    oblast: "Вінницька",
    population: 369000,
    is_demo_city: false,
  },
  {
    slug: "poltava",
    name_uk: "Полтава",
    oblast: "Полтавська",
    population: 280000,
    is_demo_city: false,
  },
  { slug: "lutsk", name_uk: "Луцьк", oblast: "Волинська", population: 217000, is_demo_city: false },
  {
    slug: "ivano-frankivsk",
    name_uk: "Івано-Франківськ",
    oblast: "Івано-Франківська",
    population: 238000,
    is_demo_city: false,
  },
  {
    slug: "rivne",
    name_uk: "Рівне",
    oblast: "Рівненська",
    population: 244000,
    is_demo_city: false,
  },
];

// --------------------------------------------------------------
// Organizations
// --------------------------------------------------------------
export type SeedOrg = {
  key: string; // local key used by events to refer to the org
  name: string;
  contact_name: string;
  contact_phone: string;
  contact_telegram: string;
  type: string;
  city: string;
  oblast: string;
  verified: boolean;
};

export const SEED_ORGS: SeedOrg[] = [
  {
    key: "poruch_kyiv",
    name: "ГО «Просвіт» — Київський осередок",
    contact_name: "Олена",
    contact_phone: "+380440000001",
    contact_telegram: "@poruch_kyiv",
    type: "go",
    city: "Київ",
    oblast: "Київська",
    verified: true,
  },
  {
    key: "lisova_polyana",
    name: "Реабілітаційний центр «Лісова Поляна»",
    contact_name: "Світлана",
    contact_phone: "+380440000002",
    contact_telegram: "@lisova_polyana",
    type: "rehab_center",
    city: "Київ",
    oblast: "Київська",
    verified: true,
  },
  {
    key: "atlet_sport",
    name: "Спортивний клуб «Атлет»",
    contact_name: "Сергій",
    contact_phone: "+380440000003",
    contact_telegram: "@atlet_kyiv",
    type: "sport_club",
    city: "Київ",
    oblast: "Київська",
    verified: true,
  },
  {
    key: "kobylianska_lib",
    name: "Бібліотека імені Ольги Кобилянської",
    contact_name: "Олександра",
    contact_phone: "+380440000004",
    contact_telegram: "@kobylianska_lib",
    type: "library",
    city: "Київ",
    oblast: "Київська",
    verified: true,
  },
  {
    key: "zhinochyi_prostir",
    name: "ГО «Жіночий простір»",
    contact_name: "Марія",
    contact_phone: "+380320000005",
    contact_telegram: "@zh_prostir",
    type: "go",
    city: "Львів",
    oblast: "Львівська",
    verified: true,
  },
  {
    key: "lviv_lib",
    name: "Львівська міська бібліотека",
    contact_name: "Богдан",
    contact_phone: "+380320000006",
    contact_telegram: "@lviv_library",
    type: "library",
    city: "Львів",
    oblast: "Львівська",
    verified: true,
  },
  {
    key: "dnipro_community",
    name: "Дніпровська ветеранська спільнота",
    contact_name: "Юрій",
    contact_phone: "+380560000007",
    contact_telegram: "@dnipro_vets",
    type: "go",
    city: "Дніпро",
    oblast: "Дніпропетровська",
    verified: true,
  },
];

// --------------------------------------------------------------
// Ghost veterans (display names only — no tg_user_id; used for social proof)
// --------------------------------------------------------------
export type SeedGhost = {
  display_name: string;
  city: string;
  interests: InterestCategory[];
  accessibility_flags: AccessibilityFlag[];
};

export const SEED_GHOSTS: SeedGhost[] = [
  // Київ — 10
  {
    display_name: "Олег",
    city: "Київ",
    interests: ["movement", "community"],
    accessibility_flags: [],
  },
  {
    display_name: "Андрій",
    city: "Київ",
    interests: ["movement", "walks"],
    accessibility_flags: [],
  },
  {
    display_name: "Анна",
    city: "Київ",
    interests: ["craft", "community"],
    accessibility_flags: [],
  },
  {
    display_name: "Світлана",
    city: "Київ",
    interests: ["community", "reading"],
    accessibility_flags: ["quiet_room"],
  },
  {
    display_name: "Тарас",
    city: "Київ",
    interests: ["movement"],
    accessibility_flags: ["barrier_free"],
  },
  { display_name: "Олена", city: "Київ", interests: ["craft", "reading"], accessibility_flags: [] },
  {
    display_name: "Сергій",
    city: "Київ",
    interests: ["movement", "volunteering"],
    accessibility_flags: [],
  },
  { display_name: "Ірина", city: "Київ", interests: ["walks", "reading"], accessibility_flags: [] },
  {
    display_name: "Артем",
    city: "Київ",
    interests: ["learning", "community"],
    accessibility_flags: ["barrier_free", "no_stairs"],
  },
  { display_name: "Юлія", city: "Київ", interests: ["family", "walks"], accessibility_flags: [] },

  // Львів — 9
  {
    display_name: "Богдан",
    city: "Львів",
    interests: ["movement", "community"],
    accessibility_flags: [],
  },
  {
    display_name: "Юрій",
    city: "Львів",
    interests: ["craft", "learning"],
    accessibility_flags: [],
  },
  {
    display_name: "Оксана",
    city: "Львів",
    interests: ["craft", "community"],
    accessibility_flags: [],
  },
  {
    display_name: "Марія",
    city: "Львів",
    interests: ["reading", "walks"],
    accessibility_flags: [],
  },
  {
    display_name: "Володимир",
    city: "Львів",
    interests: ["volunteering", "community"],
    accessibility_flags: [],
  },
  {
    display_name: "Тетяна",
    city: "Львів",
    interests: ["craft", "reading"],
    accessibility_flags: ["quiet_room"],
  },
  { display_name: "Микола", city: "Львів", interests: ["movement"], accessibility_flags: [] },
  {
    display_name: "Леся",
    city: "Львів",
    interests: ["craft"],
    accessibility_flags: ["barrier_free"],
  },
  {
    display_name: "Денис",
    city: "Львів",
    interests: ["learning", "movement"],
    accessibility_flags: [],
  },

  // Дніпро — 7
  { display_name: "Ігор", city: "Дніпро", interests: ["movement"], accessibility_flags: [] },
  {
    display_name: "Наталя",
    city: "Дніпро",
    interests: ["movement", "walks"],
    accessibility_flags: [],
  },
  {
    display_name: "Олексій",
    city: "Дніпро",
    interests: ["volunteering"],
    accessibility_flags: [],
  },
  {
    display_name: "Дарина",
    city: "Дніпро",
    interests: ["reading", "community"],
    accessibility_flags: [],
  },
  {
    display_name: "Назар",
    city: "Дніпро",
    interests: ["movement", "craft"],
    accessibility_flags: [],
  },
  { display_name: "Роман", city: "Дніпро", interests: ["walks"], accessibility_flags: [] },
  {
    display_name: "Павло",
    city: "Дніпро",
    interests: ["community"],
    accessibility_flags: ["sign_language"],
  },
];

// --------------------------------------------------------------
// Events
// --------------------------------------------------------------
export type SeedEvent = {
  slug: string;
  title: string;
  short_description: string;
  description: string;
  organizer_key: string;
  city: string;
  oblast: string;
  address: string;
  location_lat: number;
  location_lng: number;
  // start_at is computed as today+days_from_today at hour:minute (Europe/Kyiv)
  days_from_today: number;
  hour: number;
  minute: number;
  duration_min: number;
  categories: InterestCategory[];
  identity_tag: IdentityPref;
  accessibility_flags: AccessibilityFlag[];
  honest_absences: string[];
  price_uah: number;
  what_to_bring: string[];
  // Tunable to make some events more "popular" than others.
  ghost_count: number;
};

const KYIV = { city: "Київ", oblast: "Київська" };
const LVIV = { city: "Львів", oblast: "Львівська" };
const DNIPRO = { city: "Дніпро", oblast: "Дніпропетровська" };

export const SEED_EVENTS: SeedEvent[] = [
  // ============= Київ — 12 events =============
  {
    slug: "futbol-shevchenka-kyiv",
    title: "Футбол з ветеранами у парку Шевченка",
    short_description: "Невелика гра у парку — без рівня, просто пограти.",
    description:
      "Зустріч на 90 хвилин: розминка, дві команди, легка гра. Беремо одного-двох новачків кожного разу — нікого не залишаємо на лаві.\n\nВходу на поле — два рівні підходи, без сходів. Якщо бракує форми, є запасні футболки і бутси у Олега.",
    organizer_key: "atlet_sport",
    ...KYIV,
    address: "Парк Шевченка, біля південного входу",
    location_lat: 50.4434,
    location_lng: 30.5103,
    days_from_today: 1,
    hour: 18,
    minute: 0,
    duration_min: 90,
    categories: ["movement", "community"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "no_stairs"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: ["Зручне взуття", "Воду"],
    ghost_count: 6,
  },
  {
    slug: "adaptyvne-plavannia-khvylya",
    title: "Адаптивне плавання у басейні «Хвиля»",
    short_description: "Спокійне плавання в окремій доріжці. Тренер у воді.",
    description:
      "Тренер Світлана сама ходить з протезом — її дорожка тиха, без хлораки і шуму, з підйомником у воду.\n\nМожна без досвіду. Рушник і окуляри для плавання — є запасні в басейні, питай Світлану.",
    organizer_key: "lisova_polyana",
    ...KYIV,
    address: "Басейн «Хвиля», вул. Бойчука 10",
    location_lat: 50.4187,
    location_lng: 30.5635,
    days_from_today: 2,
    hour: 17,
    minute: 0,
    duration_min: 75,
    categories: ["movement"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "no_stairs", "quiet_room", "parking_disabled"],
    honest_absences: ["роздягальня без лежака"],
    price_uah: 0,
    what_to_bring: ["Купальник або шорти", "Шапочку для плавання"],
    ghost_count: 5,
  },
  {
    slug: "rozmovnyy-klub-zhinky-kyiv",
    title: "Розмовний клуб для жінок-ветеранок",
    short_description: "Камерна група. Можна мовчати, можна питати.",
    description:
      "Збираємося у тихій кімнаті бібліотеки. До восьми людей. Веде психологиня з ветеранського досвіду.\n\nГотуємо чай, говоримо про що хочеш — або просто слухаєш. Стільки разів, скільки треба тобі.",
    organizer_key: "kobylianska_lib",
    ...KYIV,
    address: "Бібліотека ім. Кобилянської, вул. Турівська 13",
    location_lat: 50.4683,
    location_lng: 30.5137,
    days_from_today: 3,
    hour: 18,
    minute: 30,
    duration_min: 90,
    categories: ["community"],
    identity_tag: "women_only",
    accessibility_flags: ["barrier_free", "no_stairs", "quiet_room", "no_alcohol"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: [],
    ghost_count: 4,
  },
  {
    slug: "yoga-holosiivskyi-park",
    title: "Йога у Голосіївському парку",
    short_description: "Ранкова практика на килимках. Початковий рівень.",
    description:
      "Зустріч на галявині біля третього озера. Беремо килимки, якщо є — є запасні три у Артема.\n\nПрактика спокійна: дихання, легкі асани, розслаблення. Без фотозйомки.",
    organizer_key: "atlet_sport",
    ...KYIV,
    address: "Голосіївський парк, галявина біля третього озера",
    location_lat: 50.3894,
    location_lng: 30.4944,
    days_from_today: 2,
    hour: 9,
    minute: 0,
    duration_min: 60,
    categories: ["movement"],
    identity_tag: "any",
    accessibility_flags: ["no_alcohol"],
    honest_absences: ["до галявини — стежка через корені"],
    price_uah: 0,
    what_to_bring: ["Килимок (якщо є)", "Воду"],
    ghost_count: 4,
  },
  {
    slug: "remont-velosypediv-kyiv",
    title: "Майстерня з ремонту велосипедів",
    short_description: "Навчимо від проколу до перебирання заднього колеса.",
    description:
      "У майстерні є все: ключі, насос, мастило. Беремо свій велосипед, або просто прийти подивитися.\n\nВеде Богдан — механік 12 років. Спокійний, повторить стільки разів, скільки треба.",
    organizer_key: "poruch_kyiv",
    ...KYIV,
    address: "Велосипедна майстерня «На колесах», вул. Січових Стрільців 77",
    location_lat: 50.4554,
    location_lng: 30.4948,
    days_from_today: 4,
    hour: 14,
    minute: 0,
    duration_min: 120,
    categories: ["craft", "learning"],
    identity_tag: "men_only",
    accessibility_flags: [],
    honest_absences: ["сходи на вході — 3 сходинки"],
    price_uah: 0,
    what_to_bring: ["Свій велосипед, якщо є"],
    ghost_count: 3,
  },
  {
    slug: "kava-cholovichi-rozmovy-kyiv",
    title: "Чоловічі розмови за кавою",
    short_description: "Кава, тиша, говоримо тільки коли хочеться.",
    description:
      "У тихому залі кав'ярні «Своя» збираємо невелику групу. Кава за рахунок організаторів — перші дві чашки.\n\nТем не задаємо. Якщо людина не говорить — то і не питаємо. Ніяких порад «треба триматися».",
    organizer_key: "poruch_kyiv",
    ...KYIV,
    address: "Кав'ярня «Своя», вул. Жилянська 47",
    location_lat: 50.4408,
    location_lng: 30.5038,
    days_from_today: 5,
    hour: 19,
    minute: 0,
    duration_min: 90,
    categories: ["community"],
    identity_tag: "men_only",
    accessibility_flags: ["barrier_free", "no_alcohol"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: [],
    ghost_count: 5,
  },
  {
    slug: "andriivskyi-uzviz-walk",
    title: "Прогулянка по Андріївському узвозу",
    short_description: "Спокійна прогулянка з гідом. Дві години.",
    description:
      "Гід Олена — місцевий екскурсовод, проводить такі прогулянки безкоштовно для ветеранів.\n\nТемп середній: зупинки кожні 15 хвилин. Маршрут вниз — нагору не йдемо.",
    organizer_key: "poruch_kyiv",
    ...KYIV,
    address: "Початок: Андріївська церква",
    location_lat: 50.4595,
    location_lng: 30.5182,
    days_from_today: 6,
    hour: 11,
    minute: 0,
    duration_min: 120,
    categories: ["walks"],
    identity_tag: "any",
    accessibility_flags: [],
    honest_absences: ["бруківка нерівна — на кріслі складно"],
    price_uah: 0,
    what_to_bring: ["Зручне взуття", "Парасольку, якщо хмарно"],
    ghost_count: 4,
  },
  {
    slug: "knyzhkovyi-klub-kobylianska",
    title: "Книжковий клуб у бібліотеці Кобилянської",
    short_description: "Читаємо одну книгу разом, обговорюємо раз на тиждень.",
    description:
      "Цього місяця читаємо «Я бачу, вас цікавить пітьма» Сергія Жадана. Книги є у бібліотеці, можна забрати.\n\nЗустріч у тихій кімнаті. Можна не дочитати — все одно приходь, послухати.",
    organizer_key: "kobylianska_lib",
    ...KYIV,
    address: "Бібліотека ім. Кобилянської, тиха кімната",
    location_lat: 50.4683,
    location_lng: 30.5137,
    days_from_today: 7,
    hour: 18,
    minute: 0,
    duration_min: 90,
    categories: ["reading", "community"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "no_stairs", "quiet_room"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: [],
    ghost_count: 4,
  },
  {
    slug: "honcharstvo-spilna-maisternia",
    title: "Гончарство — спільна майстерня",
    short_description: "Робиш чашку або тарілку. З нуля, за дві години.",
    description:
      "Глина, гончарне коло, інструмент — усе є. Веде Олена, гончарка з 8-річним досвідом.\n\nГотовий виріб залишається у тебе — забереш через тиждень після випалу. Безкоштовно для ветеранів.",
    organizer_key: "poruch_kyiv",
    ...KYIV,
    address: "Майстерня «Глина», вул. Костянтинівська 22",
    location_lat: 50.4647,
    location_lng: 30.5119,
    days_from_today: 8,
    hour: 15,
    minute: 0,
    duration_min: 120,
    categories: ["craft"],
    identity_tag: "any",
    accessibility_flags: ["no_alcohol"],
    honest_absences: ["сходи 5 сходинок при вході"],
    price_uah: 0,
    what_to_bring: ["Стара футболка (брудно)"],
    ghost_count: 3,
  },
  {
    slug: "simeinyi-den-hidropark",
    title: "Сімейний день у Гідропарку",
    short_description: "Беремо дітей, друзів, родину. Все на свіжому повітрі.",
    description:
      "Зустрічаємось біля велопрокату. Спортивні ігри для дітей, шахи для дорослих, термос з чаєм.\n\nДіти від 5 років — ок. Молодше — теж приходь, пісочниця поруч.",
    organizer_key: "poruch_kyiv",
    ...KYIV,
    address: "Гідропарк, біля велопрокату",
    location_lat: 50.4566,
    location_lng: 30.5683,
    days_from_today: 9,
    hour: 12,
    minute: 0,
    duration_min: 180,
    categories: ["family", "community"],
    identity_tag: "family_friendly",
    accessibility_flags: ["barrier_free", "no_stairs"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: ["Плед, якщо хочеш"],
    ghost_count: 5,
  },
  {
    slug: "shakhy-desnianskyi-prostir",
    title: "Шахи у Деснянському просторі",
    short_description: "Турнір для всіх рівнів. Дошки і годинник на місці.",
    description:
      "Можна без шахових знань — навчимо за 15 хвилин. Турнір швейцарською системою, 4 раунди по 30 хвилин.\n\nВходить чай, печиво. Переможцю — не приз, а просто потиснемо руку.",
    organizer_key: "poruch_kyiv",
    ...KYIV,
    address: "Простір «Десна», просп. Маяковського 30",
    location_lat: 50.4978,
    location_lng: 30.6336,
    days_from_today: 5,
    hour: 16,
    minute: 0,
    duration_min: 180,
    categories: ["learning", "community"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "no_stairs", "quiet_room"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: [],
    ghost_count: 4,
  },
  {
    slug: "prytulok-tvaryny-volonter-kyiv",
    title: "Допомога у притулку для тварин",
    short_description: "Прогулянки з собаками, прибирання. Без фізнавантаження.",
    description:
      "Притулок «Сіріус» — півгодини на електричці. Не просять багато: погуляти з собакою, помити миски.\n\nПісля можна залишитися на чай у волонтерській кімнаті. Часто потім хочеться повернутися.",
    organizer_key: "poruch_kyiv",
    ...KYIV,
    address: "Притулок «Сіріус», смт Бородянка",
    location_lat: 50.6489,
    location_lng: 29.9203,
    days_from_today: 6,
    hour: 10,
    minute: 0,
    duration_min: 240,
    categories: ["volunteering"],
    identity_tag: "any",
    accessibility_flags: [],
    honest_absences: ["підлога нерівна, місцями бруд"],
    price_uah: 0,
    what_to_bring: ["Старий одяг", "Гумові чоботи, якщо є"],
    ghost_count: 3,
  },

  // ============= Львів — 10 events =============
  {
    slug: "lviv-ekskursiia-veterany",
    title: "Екскурсія старим Львовом для ветеранів",
    short_description: "Маршрут уникає сходів і бруківки де можна.",
    description:
      "Гід Микола — місцевий, водить тільки спокійні маршрути. Тривалість дві години, з зупинкою на каву.\n\nГрупа невелика — до восьми людей. Темп розмірений, питай скільки хочеш.",
    organizer_key: "lviv_lib",
    ...LVIV,
    address: "Початок: пам'ятник Шевченку",
    location_lat: 49.8419,
    location_lng: 24.0316,
    days_from_today: 2,
    hour: 11,
    minute: 0,
    duration_min: 120,
    categories: ["walks", "community"],
    identity_tag: "any",
    accessibility_flags: [],
    honest_absences: ["бруківка по ходу — складно з кріслом"],
    price_uah: 0,
    what_to_bring: ["Зручне взуття"],
    ghost_count: 5,
  },
  {
    slug: "zhinoche-remeslo-honcharstvo-lviv",
    title: "Жіноче ремесло — гончарство і кава",
    short_description: "Невелика жіноча група. Глина і кава за чашкою.",
    description:
      "Зустріч у тихій майстерні. Гончарне коло є для кожної. Веде Оксана — сама ветеранка, спокійно вчить навіть тих, хто ніколи не чіпав глину.\n\nБерем чашку чи тарілку — заберете через тиждень, після випалу. Питання можна — або просто мовчати поруч.",
    organizer_key: "zhinochyi_prostir",
    ...LVIV,
    address: "Майстерня «Глина і чай», вул. Сахарова 42",
    location_lat: 49.8244,
    location_lng: 24.0099,
    days_from_today: 3,
    hour: 11,
    minute: 0,
    duration_min: 150,
    categories: ["craft", "community"],
    identity_tag: "women_only",
    accessibility_flags: ["barrier_free", "no_stairs", "quiet_room", "no_alcohol"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: ["Стара футболка"],
    ghost_count: 4,
  },
  {
    slug: "basketbol-shkola-7-lviv",
    title: "Баскетбол у спортивній школі №7",
    short_description: "Любительська гра. Без рівня, з тренером.",
    description:
      "Зал — це нормально, з паркетом. Тренер Володимир розводить команди по силі, ніхто не сидить на лаві.\n\nПісля гри — душ і чай. Беремо своїх кросівок — паркет.",
    organizer_key: "zhinochyi_prostir",
    ...LVIV,
    address: "Спортшкола №7, вул. Самійленка 5",
    location_lat: 49.8501,
    location_lng: 24.0287,
    days_from_today: 4,
    hour: 19,
    minute: 0,
    duration_min: 90,
    categories: ["movement"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "no_stairs"],
    honest_absences: ["туалет не адаптований"],
    price_uah: 0,
    what_to_bring: ["Кросівки нескользкі", "Воду"],
    ghost_count: 4,
  },
  {
    slug: "karpaty-pohid-veterany",
    title: "Похід у Карпати — група ветеранів",
    short_description: "Один день. Несильний маршрут. Треба підготовка.",
    description:
      "Виїзд автобусом о 6-й, повернення близько 21:00. Маршрут — гора Маківка, 12 км, перепад 400 м. Якщо не ходив раніше — попередь Богдана, підкаже взуття і темп.\n\nНе екстрим. Зупинки кожні 30 хвилин. На вершині — чай і бутерброди.",
    organizer_key: "zhinochyi_prostir",
    ...LVIV,
    address: "Збір біля автостанції «Стрийська»",
    location_lat: 49.7872,
    location_lng: 24.0066,
    days_from_today: 9,
    hour: 6,
    minute: 0,
    duration_min: 900,
    categories: ["movement", "walks"],
    identity_tag: "any",
    accessibility_flags: [],
    honest_absences: ["потребує підготовки і трекінгових кросівок"],
    price_uah: 150,
    what_to_bring: ["Трекінгове взуття", "Куртку від дощу", "Воду 1.5 л"],
    ghost_count: 6,
  },
  {
    slug: "zhinochyi-klub-pysma-lviv",
    title: "Жіночий клуб письма",
    short_description: "Пишемо, читаємо вголос — або не читаємо. Як хочеш.",
    description:
      "Збираємось у тихій кімнаті бібліотеки. Дві години: 30 хв на тиху практику, 60 хв обговорення, 30 хв чай.\n\nНе «терапевтичний» клуб. Просто пишемо, ділимось, якщо хочемо. Ведуча Леся — поетка.",
    organizer_key: "lviv_lib",
    ...LVIV,
    address: "Львівська міська бібліотека, тиха кімната",
    location_lat: 49.8418,
    location_lng: 24.0259,
    days_from_today: 5,
    hour: 18,
    minute: 0,
    duration_min: 120,
    categories: ["craft", "community"],
    identity_tag: "women_only",
    accessibility_flags: ["barrier_free", "quiet_room", "no_alcohol"],
    honest_absences: ["сходи 4 сходинки при вході"],
    price_uah: 0,
    what_to_bring: ["Зошит, ручку"],
    ghost_count: 3,
  },
  {
    slug: "kulinarna-vecheria-spilno-lviv",
    title: "Кулінарна вечеря — спільна готовка",
    short_description: "Готуємо разом, потім разом їмо. Без алкоголю.",
    description:
      "Цього разу — борщ і вареники. Усі продукти куплено, ножі і дошки є.\n\nЯкщо не готував раніше — все одно приходь, є робота для всіх. Після їжі — мити посуд разом.",
    organizer_key: "zhinochyi_prostir",
    ...LVIV,
    address: "Кулінарна студія «Спільне», вул. Городоцька 110",
    location_lat: 49.8367,
    location_lng: 23.9941,
    days_from_today: 6,
    hour: 17,
    minute: 0,
    duration_min: 180,
    categories: ["learning", "community"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "no_alcohol", "no_stairs"],
    honest_absences: [],
    price_uah: 100,
    what_to_bring: ["Фартух (є запасні)"],
    ghost_count: 4,
  },
  {
    slug: "restavratsiia-foto-lviv",
    title: "Реставрація старих фотографій",
    short_description: "Сканування, чистка, ретуш. Принось свої фото.",
    description:
      "Якщо є старі сімейні фото, які бліднуть — приноси оригінали або скани. Допоможемо зберегти.\n\nТехніка є: сканер, два комп'ютери з Photoshop. Веде Юрій — фотограф 20 років.",
    organizer_key: "lviv_lib",
    ...LVIV,
    address: "Львівська бібліотека, медіа-кімната",
    location_lat: 49.8418,
    location_lng: 24.0259,
    days_from_today: 4,
    hour: 14,
    minute: 0,
    duration_min: 180,
    categories: ["craft", "learning"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "quiet_room"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: ["Старі фото або скани на флешці"],
    ghost_count: 3,
  },
  {
    slug: "rankova-probizhka-stryiskyi-lviv",
    title: "Ранкова пробіжка у парку Стрийському",
    short_description: "Легкий темп. Можна йти швидким кроком.",
    description:
      "Зустріч біля головного входу до парку. Один круг — 4 км, темп 6:30/км. Хто хоче — два круги.\n\nПісля — кава у «На каменях». За свій рахунок, але дешево.",
    organizer_key: "zhinochyi_prostir",
    ...LVIV,
    address: "Стрийський парк, головний вхід",
    location_lat: 49.8197,
    location_lng: 24.0249,
    days_from_today: 2,
    hour: 8,
    minute: 0,
    duration_min: 60,
    categories: ["movement"],
    identity_tag: "any",
    accessibility_flags: [],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: ["Кросівки", "Воду"],
    ghost_count: 4,
  },
  {
    slug: "tykha-kimnata-rozmovy-lviv",
    title: "Тиха кімната для розмов — щотижня",
    short_description: "Малі групи, тиша між фразами. Можна просто сидіти.",
    description:
      "Цикл щотижня. Камерна група до восьми людей. Веде Тетяна — соціальна працівниця з ветеранського досвіду.\n\nГоворимо коли хочеться. Якщо тиша 10 хвилин — то і нормально. Чай завжди є.",
    organizer_key: "zhinochyi_prostir",
    ...LVIV,
    address: "Простір «Тиха», вул. Шевченка 60",
    location_lat: 49.8531,
    location_lng: 24.0192,
    days_from_today: 7,
    hour: 18,
    minute: 30,
    duration_min: 90,
    categories: ["community"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "no_stairs", "quiet_room", "no_alcohol"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: [],
    ghost_count: 4,
  },
  {
    slug: "obrobka-dereva-maisternia-lviv",
    title: "Майстерня з обробки дерева",
    short_description: "Робиш дошку для нарізання або підставку. З нуля.",
    description:
      "Інструмент, дерево, захист — все на місці. Веде Денис, столяр.\n\nГотовий виріб забираєш. Перший раз — простіше: дошка для нарізки. Хто був раніше — підставка під каву.",
    organizer_key: "zhinochyi_prostir",
    ...LVIV,
    address: "Столярна майстерня «Дерево», вул. Зелена 84",
    location_lat: 49.8174,
    location_lng: 24.0451,
    days_from_today: 8,
    hour: 14,
    minute: 0,
    duration_min: 180,
    categories: ["craft", "learning"],
    identity_tag: "men_only",
    accessibility_flags: [],
    honest_absences: ["сходи 3 сходинки на вході", "ваги до 10 кг тримати треба"],
    price_uah: 80,
    what_to_bring: ["Стара одежа"],
    ghost_count: 3,
  },

  // ============= Дніпро — 8 events =============
  {
    slug: "velo-naberezhna-dnipro",
    title: "Велопробіг набережною Дніпра",
    short_description: "12 км по рівній набережній. Темп комфортний.",
    description:
      "Старт біля моста — їдемо вниз до набережної Перемоги і назад. Один привал, 15 хв.\n\nВелосипед — твій або взяти у прокаті біля старту (50 грн/година). Пишемо у чат, якщо потрібно.",
    organizer_key: "dnipro_community",
    ...DNIPRO,
    address: "Набережна Дніпра, біля Центрального моста",
    location_lat: 48.4544,
    location_lng: 35.0636,
    days_from_today: 3,
    hour: 10,
    minute: 0,
    duration_min: 120,
    categories: ["movement"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: ["Велосипед або кошти на прокат", "Воду"],
    ghost_count: 5,
  },
  {
    slug: "foto-prohulianka-dnipro",
    title: "Фото-прогулянка містом",
    short_description: "Знімаємо на телефон. Без претензій до техніки.",
    description:
      "Маршрут — від парку Шевченка до набережної. Дві години, зупинки на цікаві ракурси.\n\nВ кінці — обираємо одне фото від кожного, обговорюємо. Без оцінок «гарно/негарно».",
    organizer_key: "dnipro_community",
    ...DNIPRO,
    address: "Парк Шевченка, центральний вхід",
    location_lat: 48.4548,
    location_lng: 35.0556,
    days_from_today: 4,
    hour: 11,
    minute: 0,
    duration_min: 120,
    categories: ["craft", "walks"],
    identity_tag: "any",
    accessibility_flags: [],
    honest_absences: ["частково сходи у парку"],
    price_uah: 0,
    what_to_bring: ["Заряджений телефон"],
    ghost_count: 3,
  },
  {
    slug: "zhinocha-pilates-dnipro",
    title: "Жіноча група спорту — пілатес",
    short_description: "Спокійна практика для тіла. Тренерка-ветеранка.",
    description:
      "Зал тихий, килимки на місці. Тренерка Наталя сама ветеранка — зрозуміє, якщо щось болить.\n\nПерший раз — поясняє кожну вправу окремо. Можна пропускати, якщо щось не йде.",
    organizer_key: "dnipro_community",
    ...DNIPRO,
    address: "Студія «Своя сила», вул. Воскресенська 12",
    location_lat: 48.4665,
    location_lng: 35.0455,
    days_from_today: 2,
    hour: 18,
    minute: 0,
    duration_min: 75,
    categories: ["movement"],
    identity_tag: "women_only",
    accessibility_flags: ["barrier_free", "quiet_room", "no_alcohol"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: ["Зручний одяг", "Воду"],
    ghost_count: 5,
  },
  {
    slug: "rozmovnyi-klub-pary-dnipro",
    title: "Розмовний клуб для пар",
    short_description: "Для ветеранів і їхніх близьких. Без терапії.",
    description:
      "Невелика група: 4-6 пар. Веде сімейна психологиня з 10-річним досвідом.\n\nТема цього разу — як знайти спільну тишу. Можна прийти разом, можна одному.",
    organizer_key: "dnipro_community",
    ...DNIPRO,
    address: "Простір «Поруч», вул. Гоголя 19",
    location_lat: 48.4628,
    location_lng: 35.0455,
    days_from_today: 6,
    hour: 18,
    minute: 30,
    duration_min: 90,
    categories: ["community", "family"],
    identity_tag: "family_friendly",
    accessibility_flags: ["barrier_free", "no_stairs", "quiet_room"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: [],
    ghost_count: 3,
  },
  {
    slug: "volonterstvo-livyi-bereh-dnipro",
    title: "Волонтерство на лівому березі",
    short_description: "Прибирання набережної. 3 години, кав'ярка платить.",
    description:
      "Збираємо сміття вздовж берегу 1.5 км. Інструмент і пакети є.\n\nПісля — кав'ярка «Берег» пригощає кавою і сендвічем. За 3 години роботи — нормально.",
    organizer_key: "dnipro_community",
    ...DNIPRO,
    address: "Лівий берег, біля кав'ярні «Берег»",
    location_lat: 48.4756,
    location_lng: 35.0944,
    days_from_today: 7,
    hour: 9,
    minute: 0,
    duration_min: 180,
    categories: ["volunteering"],
    identity_tag: "any",
    accessibility_flags: [],
    honest_absences: ["підлога нерівна, грязюка після дощу"],
    price_uah: 0,
    what_to_bring: ["Гумові рукавички (є запасні)", "Стара одежа"],
    ghost_count: 4,
  },
  {
    slug: "knyzhkovyi-obmin-dnipro",
    title: "Книжковий обмін у бібліотеці",
    short_description: "Принось одну, забирай одну. Або просто прийди.",
    description:
      "У читальній залі — стіл з книгами. Хто хоче — приносить свою прочитану, забирає чужу.\n\nЯкщо не приніс — теж бери. На наступний раз знайдеш що принести.",
    organizer_key: "dnipro_community",
    ...DNIPRO,
    address: "Дніпровська обласна бібліотека, читальна зала",
    location_lat: 48.4625,
    location_lng: 35.0479,
    days_from_today: 5,
    hour: 17,
    minute: 0,
    duration_min: 90,
    categories: ["reading", "community"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "no_stairs", "quiet_room"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: ["Книгу, якщо є"],
    ghost_count: 3,
  },
  {
    slug: "surdopereklad-rozmov-dnipro",
    title: "Розмовний клуб з сурдоперекладом",
    short_description: "Для глухих ветеранів і тих, хто чує. Сурдоперекладач є.",
    description:
      "Перша зустріч цикла. Тема — знайомство, чим займаєшся. Сурдоперекладачка Анна.\n\nЯкщо чуєш, але хочеш вчити жестову — теж приходь. Навчатимемо знаки в перерві.",
    organizer_key: "dnipro_community",
    ...DNIPRO,
    address: "Простір «Поруч», вул. Гоголя 19",
    location_lat: 48.4628,
    location_lng: 35.0455,
    days_from_today: 8,
    hour: 18,
    minute: 0,
    duration_min: 90,
    categories: ["community", "learning"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "no_stairs", "quiet_room", "sign_language"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: [],
    ghost_count: 3,
  },
  {
    slug: "spilne-chytannia-poezii-dnipro",
    title: "Спільне читання поезії",
    short_description: "Кожен читає одне, що йому близько. Без аналізу.",
    description:
      "Беремо вірш, який тобі чомусь близький. Один — твій, потім інших слухаєш.\n\nТихо, по черзі, без обговорення в стилі «що автор хотів сказати». Просто слухаємо.",
    organizer_key: "dnipro_community",
    ...DNIPRO,
    address: "Дніпровська бібліотека, тиха кімната",
    location_lat: 48.4625,
    location_lng: 35.0479,
    days_from_today: 4,
    hour: 19,
    minute: 0,
    duration_min: 75,
    categories: ["reading"],
    identity_tag: "any",
    accessibility_flags: ["barrier_free", "quiet_room"],
    honest_absences: [],
    price_uah: 0,
    what_to_bring: ["Один вірш — паперовий або у телефоні"],
    ghost_count: 3,
  },
];
